// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABN7D8SX1nt532VMK_tZQtwZTgzSDKW3U',
    appId: '1:211028165031:web:0da466894c177c02783682',
    messagingSenderId: '211028165031',
    projectId: 'soro-soke-f0a15',
    authDomain: 'soro-soke-f0a15.firebaseapp.com',
    storageBucket: 'soro-soke-f0a15.appspot.com',
    measurementId: 'G-MZ7FDFW4ZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5W7iOevrVJwvhVnqLaat0XQaHze2yayI',
    appId: '1:211028165031:android:397efaa8c33c6d58783682',
    messagingSenderId: '211028165031',
    projectId: 'soro-soke-f0a15',
    storageBucket: 'soro-soke-f0a15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEN03_JAIAmHzd1SvdTLj2YuETbu0o5qU',
    appId: '1:211028165031:ios:ae0404b7e3a6a88c783682',
    messagingSenderId: '211028165031',
    projectId: 'soro-soke-f0a15',
    storageBucket: 'soro-soke-f0a15.appspot.com',
    iosClientId:
        '211028165031-53uvis6lknv1q3rt64gfasdjhco163u4.apps.googleusercontent.com',
    iosBundleId: 'com.example.soroSoke',
  );
}
